export { default as CloseIcon } from './closeIcon';
export { default as CloseModalIcon } from './closeModalIcon';
export { default as CodesIcon } from './codesIcon';
export { default as EventsIcon } from './eventsIcon';
export { default as GoBackModalIcon } from './goBackModalIcon';
export { default as MenuIcon } from './menuIcon';
export { default as SearchIcon } from './searchIcon';
export { default as SettingsIcon } from './settingsIcon';
export { default as WishIcon } from './wishIcon';
